In [1]:
import glacierml as gl
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_datasets as tfds
import tensorflow_probability as tfp

2023-05-16 15:22:58.177093: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-16 15:22:58.222360: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-16 15:22:58.860069: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/sa42/miniconda3/envs/new_kernel/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import t

In [14]:
dataset = (
    tfds.load(name="wine_quality", as_supervised=True, split="train")
#     .map(lambda x, y: (x, tf.cast(y, tf.float32)))
#     .prefetch(buffer_size=dataset_size)
)
    

In [3]:
dataset

<_PrefetchDataset element_spec=({'alcohol': TensorSpec(shape=(), dtype=tf.float32, name=None), 'chlorides': TensorSpec(shape=(), dtype=tf.float32, name=None), 'citric acid': TensorSpec(shape=(), dtype=tf.float32, name=None), 'density': TensorSpec(shape=(), dtype=tf.float32, name=None), 'fixed acidity': TensorSpec(shape=(), dtype=tf.float32, name=None), 'free sulfur dioxide': TensorSpec(shape=(), dtype=tf.float32, name=None), 'pH': TensorSpec(shape=(), dtype=tf.float32, name=None), 'residual sugar': TensorSpec(shape=(), dtype=tf.float32, name=None), 'sulphates': TensorSpec(shape=(), dtype=tf.float64, name=None), 'total sulfur dioxide': TensorSpec(shape=(), dtype=tf.float32, name=None), 'volatile acidity': TensorSpec(shape=(), dtype=tf.float32, name=None)}, TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [46]:
df = gl.parameterize_data(parameterization = '4')
feat1 = df['CenLat']
feat2 = df['CenLon']
feat3 = df['Slope']
feat4 = df['Zmin']
feat5 = df['Zmed']
feat6 = df['Zmax']
feat7 = df['Area']
feat8 = df['Aspect']
feat9 = df['Area']
# feats = ['CenLat', 'CenLon', 'Slope','Zmin','Zmed','Zmax','Lmax','Area','Aspect']
labels = df['Thickness']
# feats = df[feats]
# And this too can be used the same way!
dataset = tf.data.Dataset.from_tensor_slices((
    df['CenLat'], feat2, feat3, feat4, feat5, feat6, feat7, feat8, feat9,labels
))

In [47]:
dataset

<_TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.float64, name=None), TensorSpec(shape=(), dtype=tf.float64, name=None), TensorSpec(shape=(), dtype=tf.float64, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.float64, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.float64, name=None), TensorSpec(shape=(), dtype=tf.float64, name=None))>

In [48]:
for elem in dataset:
    print(elem)

(<tf.Tensor: shape=(), dtype=float64, numpy=63.469173431>, <tf.Tensor: shape=(), dtype=float64, numpy=-146.528167725>, <tf.Tensor: shape=(), dtype=float64, numpy=12.0>, <tf.Tensor: shape=(), dtype=int64, numpy=722>, <tf.Tensor: shape=(), dtype=int64, numpy=1841>, <tf.Tensor: shape=(), dtype=int64, numpy=3081>, <tf.Tensor: shape=(), dtype=float64, numpy=234.583>, <tf.Tensor: shape=(), dtype=int64, numpy=30>, <tf.Tensor: shape=(), dtype=float64, numpy=234.583>, <tf.Tensor: shape=(), dtype=float64, numpy=235.0>)
(<tf.Tensor: shape=(), dtype=float64, numpy=63.281>, <tf.Tensor: shape=(), dtype=float64, numpy=-145.427>, <tf.Tensor: shape=(), dtype=float64, numpy=14.0>, <tf.Tensor: shape=(), dtype=int64, numpy=1162>, <tf.Tensor: shape=(), dtype=int64, numpy=1858>, <tf.Tensor: shape=(), dtype=int64, numpy=2438>, <tf.Tensor: shape=(), dtype=float64, numpy=17.567>, <tf.Tensor: shape=(), dtype=int64, numpy=172>, <tf.Tensor: shape=(), dtype=float64, numpy=17.567>, <tf.Tensor: shape=(), dtype=float

2023-05-16 15:59:55.598386: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_8' with dtype double and shape [341]
	 [[{{node Placeholder/_8}}]]


In [24]:
feats

CenLat      CenLon  Slope  Zmin  Zmed  Zmax     Area  Aspect   Lmax
0    63.469173 -146.528168   12.0   722  1841  3081  234.583      30  41911
1    63.281000 -145.427000   14.0  1162  1858  2438   17.567     172   8639
2    58.380000 -134.349000   10.0   676  1123  1494    9.528     327   6332
8    61.200000 -140.302000   14.0  2145  2509  2894    5.859     341   3374
9    51.177000 -116.330000   15.3  2390  2526  2853    0.872      69   1181
..         ...         ...    ...   ...   ...   ...      ...     ...    ...
489 -33.029600  -70.098400   29.0  2929  5121  5894    8.376     358   8560
490 -30.145400  -69.927600   29.3  4664  5187  5525    1.189     148   1596
491 -28.538700  -69.731800   16.0  4784  5234  5597    3.140     190   3349
492 -28.381400  -69.609100   11.6  5068  5406  5753    5.209      79   3782
498 -62.670700  -60.354700    6.7    10  -999   370    5.493     273   3056

[341 rows x 9 columns]

In [44]:
def get_train_and_test_splits(train_size, batch_size=1):
    # We prefetch with a buffer the same size as the dataset because th dataset
    # is very small and fits into memory.
    dataset = (
        tfds.load(name="wine_quality", as_supervised=True, split="train")
        .map(lambda x, y: (x, tf.cast(y, tf.float32)))
        .prefetch(buffer_size=dataset_size)
        .cache()
    )
    # We shuffle with a buffer the same size as the dataset.
    train_dataset = (
        dataset.take(train_size).shuffle(buffer_size=train_size).batch(batch_size)
    )
    test_dataset = dataset.skip(train_size).batch(batch_size)

    return train_dataset, test_dataset, dataset

# '''
# MY VERSION
# '''
# def get_train_and_test_splits(train_size, batch_size=1):
#     # We prefetch with a buffer the same size as the dataset because th dataset
#     df = gl.parameterize_data(parameterization = '4')
#     feat1 = df['CenLat']
#     feat2 = df['CenLon']
#     feat3 = df['Slope']
#     feat4 = df['Zmin']
#     feat5 = df['Zmed']
#     feat6 = df['Zmax']
#     feat7 = df['Area']
#     feat8 = df['Aspect']
#     feat9 = df['Area']
#     # feats = ['CenLat', 'CenLon', 'Slope','Zmin','Zmed','Zmax','Lmax','Area','Aspect']
#     labels = df['Thickness']
#     # feats = df[feats]
#     # And this too can be used the same way!
#     dataset = tf.data.Dataset.from_tensor_slices((
#         feat1, feat2, feat3, feat4, feat5, feat6, feat7, feat8, feat9,labels
#     ))
#     train_dataset = (
#         dataset.take(train_size).shuffle(buffer_size=train_size).batch(batch_size)
#     )
#     test_dataset = dataset.skip(train_size).batch(batch_size)

#     return train_dataset, test_dataset, dataset

In [36]:
hidden_units = [8, 8]
learning_rate = 0.001


def run_experiment(model, loss, train_dataset, test_dataset):

    model.compile(
        optimizer=keras.optimizers.RMSprop(learning_rate=learning_rate),
        loss=loss,
        metrics=[keras.metrics.RootMeanSquaredError()],
    )

    print("Start training the model...")
    model.fit(train_dataset, epochs=num_epochs, validation_data=test_dataset)
    print("Model training finished.")
    _, rmse = model.evaluate(train_dataset, verbose=0)
    print(f"Train RMSE: {round(rmse, 3)}")

    print("Evaluating model performance...")
    _, rmse = model.evaluate(test_dataset, verbose=0)
    print(f"Test RMSE: {round(rmse, 3)}")

In [37]:
FEATURE_NAMES = [
    "fixed acidity",
    "volatile acidity",
    "citric acid",
    "residual sugar",
    "chlorides",
    "free sulfur dioxide",
    "total sulfur dioxide",
    "density",
    "pH",
    "sulphates",
    "alcohol",
]


def create_model_inputs():
    inputs = {}
    for feature_name in FEATURE_NAMES:
        inputs[feature_name] = layers.Input(
            name=feature_name, shape=(1,), dtype=tf.float32
        )
    return inputs



# FEATURE_NAMES = [
#     'CenLat',
#     'CenLon', 
#     'Slope', 
#     'Zmin', 
#     'Zmed', 
#     'Zmax', 
#     'Area',
#     'Aspect', 
#     'Lmax']


# def create_model_inputs():
#     inputs = {}
#     for feature_name in FEATURE_NAMES:
#         inputs[feature_name] = layers.Input(
#             name=feature_name, shape=(1,), dtype=tf.float32
#         )
#     return inputs

In [38]:
def create_baseline_model():
    inputs = create_model_inputs()
    input_values = [value for _, value in sorted(inputs.items())]
    features = keras.layers.concatenate(input_values)
    features = layers.BatchNormalization()(features)

    # Create hidden layers with deterministic weights using the Dense layer.
    for units in hidden_units:
        features = layers.Dense(units, activation="sigmoid")(features)
    # The output is deterministic: a single point estimate.
    outputs = layers.Dense(units=1)(features)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

In [39]:
# dataset_size = 4898
# batch_size = 256
# train_size = int(dataset_size * 0.85)
# train_dataset, test_dataset = get_train_and_test_splits(train_size, batch_size)

In [40]:
dataset_size = 341
batch_size = 10
train_size = int(dataset_size * 0.80)
train_dataset, test_dataset, dataset = get_train_and_test_splits(train_size, batch_size)

In [41]:
inputs = create_model_inputs()
inputs

{'fixed acidity': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'fixed acidity')>,
 'volatile acidity': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'volatile acidity')>,
 'citric acid': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'citric acid')>,
 'residual sugar': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'residual sugar')>,
 'chlorides': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'chlorides')>,
 'free sulfur dioxide': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'free sulfur dioxide')>,
 'total sulfur dioxide': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'total sulfur dioxide')>,
 'density': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'density')>,
 'pH': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'pH')>,
 'sulphates': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'sulphates')>,
 'alcohol': <KerasTensor: shap

In [42]:
num_epochs = 100
mse_loss = keras.losses.MeanAbsoluteError()
baseline_model = create_baseline_model()
run_experiment(baseline_model, mse_loss, train_dataset, test_dataset)

Start training the model...
Epoch 1/100


2023-05-16 15:50:04.413786: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int64 and shape [1]
	 [[{{node Placeholder/_4}}]]
2023-05-16 15:50:04.414307: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_3' with dtype int64 and shape [1]
	 [[{{node Placeholder/_3}}]]


 1/28 [>.............................] - ETA: 13s - loss: 6.2984 - root_mean_squared_error: 6.3197

2023-05-16 15:50:04.926472: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2023-05-16 15:50:05.010880: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int64 and shape [1]
	 [[{{node Placeholder/_4}}]]
2023-05-16 15:50:05.011301: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a val

28/28 [==============================] - 1s 24ms/step - loss: 6.4980 - root_mean_squared_error: 6.5652 - val_loss: 6.2919 - val_root_mean_squared_error: 6.3539
Epoch 2/100
28/28 [==============================] - 0s 15ms/step - loss: 6.2374 - root_mean_squared_error: 6.3094 - val_loss: 6.0714 - val_root_mean_squared_error: 6.1355
Epoch 3/100
28/28 [==============================] - 0s 14ms/step - loss: 6.0035 - root_mean_squared_error: 6.0773 - val_loss: 5.8514 - val_root_mean_squared_error: 5.9180
Epoch 4/100
28/28 [==============================] - 1s 26ms/step - loss: 5.7791 - root_mean_squared_error: 5.8551 - val_loss: 5.6362 - val_root_mean_squared_error: 5.7054
Epoch 5/100
28/28 [==============================] - 1s 26ms/step - loss: 5.5618 - root_mean_squared_error: 5.6407 - val_loss: 5.4268 - val_root_mean_squared_error: 5.4988
Epoch 6/100
28/28 [==============================] - 1s 24ms/step - loss: 5.3515 - root_mean_squared_error: 5.4334 - val_loss: 5.2209 - val_root_mean_sq

28/28 [==============================] - 0s 15ms/step - loss: 0.6675 - root_mean_squared_error: 0.9362 - val_loss: 0.6384 - val_root_mean_squared_error: 0.8875
Epoch 49/100
28/28 [==============================] - 0s 14ms/step - loss: 0.6685 - root_mean_squared_error: 0.9365 - val_loss: 0.6342 - val_root_mean_squared_error: 0.8926
Epoch 50/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6675 - root_mean_squared_error: 0.9369 - val_loss: 0.6317 - val_root_mean_squared_error: 0.8897
Epoch 51/100
28/28 [==============================] - 0s 14ms/step - loss: 0.6678 - root_mean_squared_error: 0.9367 - val_loss: 0.6363 - val_root_mean_squared_error: 0.8930
Epoch 52/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6678 - root_mean_squared_error: 0.9368 - val_loss: 0.6347 - val_root_mean_squared_error: 0.8926
Epoch 53/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6671 - root_mean_squared_error: 0.9367 - val_loss: 0.6320 - val_root_me

28/28 [==============================] - 0s 15ms/step - loss: 0.6647 - root_mean_squared_error: 0.9299 - val_loss: 0.6269 - val_root_mean_squared_error: 0.8843
Epoch 96/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6646 - root_mean_squared_error: 0.9298 - val_loss: 0.6268 - val_root_mean_squared_error: 0.8842
Epoch 97/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6650 - root_mean_squared_error: 0.9302 - val_loss: 0.6291 - val_root_mean_squared_error: 0.8819
Epoch 98/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6652 - root_mean_squared_error: 0.9300 - val_loss: 0.6268 - val_root_mean_squared_error: 0.8827
Epoch 99/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6647 - root_mean_squared_error: 0.9295 - val_loss: 0.6280 - val_root_mean_squared_error: 0.8842
Epoch 100/100
28/28 [==============================] - 0s 15ms/step - loss: 0.6647 - root_mean_squared_error: 0.9292 - val_loss: 0.6284 - val_root_m

In [43]:
sample = 10
examples, targets = list(test_dataset.unbatch().shuffle(batch_size * 10).batch(sample))[
    0
]

predicted = baseline_model(examples).numpy()
for idx in range(sample):
    print(f"Predicted: {round(float(predicted[idx][0]), 1)} - Actual: {targets[idx]}")

2023-05-16 15:50:51.970999: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [1]
	 [[{{node Placeholder/_0}}]]
2023-05-16 15:50:51.971754: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype string and shape [1]
	 [[{{node Placeholder/_1}}]]


Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 7
Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 5
Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 6
Predicted: 6.0 - Actual: 6


In [ ]:
# Define the prior weight distribution as Normal of mean=0 and stddev=1.
# Note that, in this example, the we prior distribution is not trainable,
# as we fix its parameters.
def prior(kernel_size, bias_size, dtype=None):
    n = kernel_size + bias_size
    prior_model = keras.Sequential(
        [
            tfp.layers.DistributionLambda(
                lambda t: tfp.distributions.MultivariateNormalDiag(
                    loc=tf.zeros(n), scale_diag=tf.ones(n)
                )
            )
        ]
    )
    return prior_model


# Define variational posterior weight distribution as multivariate Gaussian.
# Note that the learnable parameters for this distribution are the means,
# variances, and covariances.
def posterior(kernel_size, bias_size, dtype=None):
    n = kernel_size + bias_size
    posterior_model = keras.Sequential(
        [
            tfp.layers.VariableLayer(
                tfp.layers.MultivariateNormalTriL.params_size(n), dtype=dtype
            ),
            tfp.layers.MultivariateNormalTriL(n),
        ]
    )
    return posterior_model

In [ ]:
def create_bnn_model(train_size):
    inputs = create_model_inputs()
    features = keras.layers.concatenate(list(inputs.values()))
    features = layers.BatchNormalization()(features)

    # Create hidden layers with weight uncertainty using the DenseVariational layer.
    for units in hidden_units:
        features = tfp.layers.DenseVariational(
            units=units,
            make_prior_fn=prior,
            make_posterior_fn=posterior,
            kl_weight=1 / train_size,
            activation="sigmoid",
        )(features)

    # The output is deterministic: a single point estimate.
    outputs = layers.Dense(units=1)(features)
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

In [ ]:
num_epochs = 500
train_sample_size = int(train_size * 0.3)
small_train_dataset = train_dataset.unbatch().take(train_sample_size).batch(batch_size)

bnn_model_small = create_bnn_model(train_sample_size)
run_experiment(bnn_model_small, mse_loss, small_train_dataset, test_dataset)

In [ ]:
def compute_predictions(model, iterations=100):
    predicted = []
    for _ in range(iterations):
        predicted.append(model(examples).numpy())
    predicted = np.concatenate(predicted, axis=1)

    prediction_mean = np.mean(predicted, axis=1).tolist()
    prediction_min = np.min(predicted, axis=1).tolist()
    prediction_max = np.max(predicted, axis=1).tolist()
    prediction_range = (np.max(predicted, axis=1) - np.min(predicted, axis=1)).tolist()

    for idx in range(sample):
        print(
            f"Predictions mean: {round(prediction_mean[idx], 2)}, "
            f"min: {round(prediction_min[idx], 2)}, "
            f"max: {round(prediction_max[idx], 2)}, "
            f"range: {round(prediction_range[idx], 2)} - "
            f"Actual: {targets[idx]}"
        )


compute_predictions(bnn_model_small)

In [ ]:
num_epochs = 500
bnn_model_full = create_bnn_model(train_size)
run_experiment(bnn_model_full, mse_loss, train_dataset, test_dataset)

compute_predictions(bnn_model_full)

In [ ]:
def create_probablistic_bnn_model(train_size):
    inputs = create_model_inputs()
    features = keras.layers.concatenate(list(inputs.values()))
    features = layers.BatchNormalization()(features)

    # Create hidden layers with weight uncertainty using the DenseVariational layer.
    for units in hidden_units:
        features = tfp.layers.DenseVariational(
            units=units,
            make_prior_fn=prior,
            make_posterior_fn=posterior,
            kl_weight=1 / train_size,
            activation="sigmoid",
        )(features)

    # Create a probabilisticå output (Normal distribution), and use the `Dense` layer
    # to produce the parameters of the distribution.
    # We set units=2 to learn both the mean and the variance of the Normal distribution.
    distribution_params = layers.Dense(units=2)(features)
    outputs = tfp.layers.IndependentNormal(1)(distribution_params)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

In [ ]:
def negative_loglikelihood(targets, estimated_distribution):
    return -estimated_distribution.log_prob(targets)


num_epochs = 1000
prob_bnn_model = create_probablistic_bnn_model(train_size)
run_experiment(prob_bnn_model, negative_loglikelihood, train_dataset, test_dataset)

In [ ]:
prediction_distribution = prob_bnn_model(examples)
prediction_mean = prediction_distribution.mean().numpy().tolist()
prediction_stdv = prediction_distribution.stddev().numpy()

# The 95% CI is computed as mean ± (1.96 * stdv)
upper = (prediction_mean + (1.96 * prediction_stdv)).tolist()
lower = (prediction_mean - (1.96 * prediction_stdv)).tolist()
prediction_stdv = prediction_stdv.tolist()

for idx in range(sample):
    print(
        f"Prediction mean: {round(prediction_mean[idx][0], 2)}, "
        f"stddev: {round(prediction_stdv[idx][0], 2)}, "
        f"95% CI: [{round(lower[idx][0], 2)} - {round(upper[idx][0], 2)}]"
        f" - Actual: {targets[idx]}"
    )